title: Wei Chen's Homepage
url: "https://weichennone.github.io/"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

include:
  - _projects

tracking_id: G-9K3BTEKY98

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/myhomepage/"
#  - name: "Resume"
#    link: "resume.pdf"
 - name: "Contact"
   link: "contact"
